p2t2/figaro

Figaro/src/main/scala/com/cra/figaro/algorithm/learning/EMTerminationCriteria.scala, Figaro/src/main/scala/com/cra/figaro/algorithm/learning/GeneralizedEM.scala, Figaro/src/main/scala/com/cra/figaro/language/Continuous.scala, Figaro/src/main/scala/com/cra/figaro/language/Element.scala, Figaro/src/main/scala/com/cra/figaro/patterns/learning/ModelParameters.scala, Figaro/src/test/scala/com/cra/figaro/test/algorithm/learning/EMWithBPTest.scala, Figaro/src/test/scala/com/cra/figaro/test/algorithm/learning/EMWithImportanceTest.scala, Figaro/src/test/scala/com/cra/figaro/test/algorithm/learning/EMWithMHTest.scala, Figaro/src/test/scala/com/cra/figaro/test/algorithm/learning/ExpectationMaximizationTest.scala, Figaro/src/test/scala/com/cra/figaro/test/learning/ParameterTest.scala, Figaro/src/test/scala/com/cra/figaro/test/library/atomic/continuous/ContinuousTest.scala, FigaroExamples/src/main/scala/com/cra/figaro/example/OpenUniverseLearning.scala, FigaroExamples/src/main/scala/com/cra/figaro/example/SimpleLearning.scala
Add constraint removal to continuous unobserve
Add additional continuous element tests
Add scaladoc for EM methods
Add scaladoc to EM termination criteria
Add/Clean apply methods for EM termination criteria
Add additional EM tests
=> Code review tasks

Figaro/src/main/scala/com/cra/figaro/algorithm/learning/EMTerminationCriteria.scala, Figaro/src/main/scala/com/cra/figaro/algorithm/learning/GeneralizedEM.scala, Figaro/src/main/scala/com/cra/figaro/language/Continuous.scala, Figaro/src/main/scala/com/cra/figaro/language/Element.scala, Figaro/src/main/scala/com/cra/figaro/patterns/learning/ModelParameters.scala, Figaro/src/test/scala/com/cra/figaro/test/algorithm/learning/EMWithBPTest.scala, Figaro/src/test/scala/com/cra/figaro/test/algorithm/learning/EMWithImportanceTest.scala, Figaro/src/test/scala/com/cra/figaro/test/algorithm/learning/EMWithMHTest.scala, Figaro/src/test/scala/com/cra/figaro/test/algorithm/learning/ExpectationMaximizationTest.scala, Figaro/src/test/scala/com/cra/figaro/test/learning/ParameterTest.scala, Figaro/src/test/scala/com/cra/figaro/test/library/atomic/continuous/ContinuousTest.scala, FigaroExamples/src/main/scala/com/cra/figaro/example/OpenUniverseLearning.scala, FigaroExamples/src/main/scala/com/cra/figaro/example/SimpleLearning.scala
Reduce running time of new unit tests
=> Update unit tests

Figaro/src/main/scala/com/cra/figaro/algorithm/factored/beliefpropagation/InnerBPHandler.scala, Figaro/src/main/scala/com/cra/figaro/experimental/particlebp/ParticleBeliefPropagation.scala
Particle BP needed kill commands or the inner BP thread would keep running.
=> Kill for particle BP

Figaro/src/main/scala/com/cra/figaro/algorithm/factored/factors/BasicFactor.scala, Figaro/src/main/scala/com/cra/figaro/algorithm/factored/factors/Factor.scala, Figaro/src/main/scala/com/cra/figaro/algorithm/factored/factors/Factory.scala, Figaro/src/main/scala/com/cra/figaro/algorithm/factored/factors/factory/ApplyFactory.scala, Figaro/src/main/scala/com/cra/figaro/algorithm/factored/factors/factory/ComplexFactory.scala, Figaro/src/main/scala/com/cra/figaro/algorithm/factored/factors/factory/DistributionFactory.scala, Figaro/src/main/scala/com/cra/figaro/algorithm/factored/factors/factory/SelectFactory.scala, Figaro/src/main/scala/com/cra/figaro/algorithm/factored/factors/factory/StarFactory.scala
Added/updated ScalaDoc for factors and factors.factory
=> ScalaDoc updates

Figaro/src/main/scala/com/cra/figaro/language/Continuous.scala, Figaro/src/main/scala/com/cra/figaro/language/Flip.scala, Figaro/src/main/scala/com/cra/figaro/language/Parameterized.scala
Add missing Scaladoc to several methods
=> Scaladoc update

Figaro/src/main/scala/com/cra/figaro/library/collection/Container.scala, Figaro/src/main/scala/com/cra/figaro/library/collection/Process.scala, Figaro/src/test/scala/com/cra/figaro/test/library/collection/ContainerTest.scala, Figaro/src/test/scala/com/cra/figaro/test/library/collection/ProcessTest.scala
Issue #372. Collections .flatMap function is equivalent to .chain function for Processes and Containers. Also, updated the tests (copied chain tests, and tested using flatMap function)
=> collections .chain function becomes .flatMap

Figaro/src/main/scala/com/cra/figaro/algorithm/ProbEvidenceAlgorithm.scala, Figaro/src/main/scala/com/cra/figaro/algorithm/factored/beliefpropagation/BeliefPropagation.scala, Figaro/src/main/scala/com/cra/figaro/algorithm/factored/beliefpropagation/ProbEvidenceBeliefPropagation.scala, Figaro/src/main/scala/com/cra/figaro/experimental/particlebp/ParticleBeliefPropagation.scala, Figaro/src/test/scala/com/cra/figaro/test/algorithm/factored/ProbEvidenceTest.scala
Anytime Prob Evidence BP is not implemented yet as it requires some
careful refactoring since the AnytimeProbEvidence trait conflicts with
AnytimeProbQuery trait (and they both use the same BP class)
Mostly fixes issue #376
=> Added Prob Evidence BP that adheres to the correct API.

Figaro/src/main/scala/com/cra/figaro/algorithm/factored/ParticleGenerator.scala, Figaro/src/main/scala/com/cra/figaro/algorithm/factored/beliefpropagation/BasicFactorGraph.scala, Figaro/src/main/scala/com/cra/figaro/algorithm/factored/beliefpropagation/BeliefPropagation.scala, Figaro/src/main/scala/com/cra/figaro/algorithm/factored/beliefpropagation/FactorGraph.scala, Figaro/src/main/scala/com/cra/figaro/experimental/particlebp/ParticleBeliefPropagation.scala
Resampling now uses the prior as well as the posterior to assess a new sample
=> Improvements to Particle BP. 

Figaro/src/main/scala/com/cra/figaro/algorithm/decision/DecisionVariableElimination.scala, Figaro/src/main/scala/com/cra/figaro/algorithm/factored/beliefpropagation/BeliefPropagation.scala, Figaro/src/main/scala/com/cra/figaro/algorithm/factored/factors/BasicFactor.scala, Figaro/src/main/scala/com/cra/figaro/algorithm/factored/factors/ConditionalSelector.scala, Figaro/src/main/scala/com/cra/figaro/algorithm/factored/factors/Factor.scala, Figaro/src/main/scala/com/cra/figaro/algorithm/factored/factors/SparseFactor.scala, Figaro/src/test/scala/com/cra/figaro/test/algorithm/AbstractionTest.scala, Figaro/src/test/scala/com/cra/figaro/test/algorithm/decision/DecisionTestCases.scala, Figaro/src/test/scala/com/cra/figaro/test/algorithm/factored/FactorTest.scala
Adjusted tests and algorithms accordingly
Added comments and doc to ConditiionalSelector
=> Modified getIndices to return an Interable rather than a List

Figaro/src/main/scala/com/cra/figaro/algorithm/factored/factors/BasicFactor.scala, Figaro/src/main/scala/com/cra/figaro/algorithm/factored/factors/factory/SelectFactory.scala, Figaro/src/test/scala/com/cra/figaro/test/algorithm/factored/factors/SparseFactorTest.scala
Deduplicate factors before taking product (should probably be done for other ops)
Added some sparse factor unit tests
Note that there is still a bug
=> Dev3.1.0 Mods for Random VE bug #393

Figaro/src/main/scala/com/cra/figaro/library/compound/If.scala, Figaro/src/test/scala/com/cra/figaro/test/example/FirmsTest.scala, Figaro/src/test/scala/com/cra/figaro/test/library/compound/CompoundTest.scala
=> Compound If does not evaluate consequents unless needed

Figaro/src/main/scala/com/cra/figaro/algorithm/decision/DecisionVariableElimination.scala, Figaro/src/main/scala/com/cra/figaro/algorithm/factored/beliefpropagation/BasicFactorGraph.scala, Figaro/src/main/scala/com/cra/figaro/algorithm/factored/factors/BasicFactor.scala, Figaro/src/main/scala/com/cra/figaro/algorithm/factored/factors/Factor.scala, Figaro/src/main/scala/com/cra/figaro/algorithm/factored/factors/Factory.scala, Figaro/src/main/scala/com/cra/figaro/algorithm/factored/factors/SparseFactor.scala, Figaro/src/main/scala/com/cra/figaro/algorithm/factored/factors/factory/ComplexFactory.scala, Figaro/src/main/scala/com/cra/figaro/algorithm/factored/factors/factory/SelectFactory.scala, Figaro/src/main/scala/com/cra/figaro/algorithm/factored/factors/factory/StarFactory.scala, Figaro/src/main/scala/com/cra/figaro/experimental/structured/factory/ComplexFactory.scala, Figaro/src/main/scala/com/cra/figaro/experimental/structured/factory/Factory.scala, Figaro/src/main/scala/com/cra/figaro/experimental/structured/factory/SelectFactory.scala, Figaro/src/main/scala/com/cra/figaro/experimental/structured/factory/StarFactory.scala, Figaro/src/test/scala/com/cra/figaro/test/algorithm/factored/factors/FactorPerformanceTest.scala
Removed the default value in non-sparse factors, and removed the initialization when creating basic factors.
=> Updates to the factor code. 

Figaro/src/main/scala/com/cra/figaro/algorithm/factored/factors/Factor.scala, Figaro/src/main/scala/com/cra/figaro/experimental/factored/factors/BasicFactor.scala, Figaro/src/main/scala/com/cra/figaro/experimental/factored/factors/Factory.scala, Figaro/src/main/scala/com/cra/figaro/experimental/factored/factors/InternalVariable.scala, Figaro/src/main/scala/com/cra/figaro/experimental/factored/factors/factory/ChainFactory.scala, Figaro/src/test/scala/com/cra/figaro/test/algorithm/factored/factors/SparseFactorTest.scala, Figaro/src/test/scala/com/cra/figaro/test/experimental/factored/factors/factory/ChainFactorTest.scala
Defines a new Variable class InternalVariable for creating factors with having to create Elements
Includes modified versions of BasicFactor and Factory for testing.
Includes new ChainFactorTest
=> Dev3.1.0 New ChainFactor factory method

Figaro/src/main/scala/com/cra/figaro/algorithm/Online.scala, Figaro/src/main/scala/com/cra/figaro/algorithm/factored/beliefpropagation/ProbEvidenceBeliefPropagation.scala, Figaro/src/main/scala/com/cra/figaro/algorithm/factored/factors/SufficientStatisticsSemiring.scala, Figaro/src/main/scala/com/cra/figaro/algorithm/learning/GeneralizedEM.scala, Figaro/src/main/scala/com/cra/figaro/library/atomic/discrete/OneShifter.scala, Figaro/src/test/scala/com/cra/figaro/test/algorithm/AbstractionTest.scala, Figaro/src/test/scala/com/cra/figaro/test/algorithm/factored/BPTest.scala, Figaro/src/test/scala/com/cra/figaro/test/algorithm/factored/ProbEvidenceTest.scala, Figaro/src/test/scala/com/cra/figaro/test/algorithm/factored/SemiringTest.scala, Figaro/src/test/scala/com/cra/figaro/test/algorithm/learning/ExpectationMaximizationTest.scala, Figaro/src/test/scala/com/cra/figaro/test/algorithm/learning/OnlineEMTest.scala, Figaro/src/test/scala/com/cra/figaro/test/algorithm/learning/SufficientStatisticsVariableEliminationTest.scala, Figaro/src/test/scala/com/cra/figaro/test/algorithm/sampling/AnnealingTest.scala, Figaro/src/test/scala/com/cra/figaro/test/algorithm/sampling/ElementSamplerTest.scala, Figaro/src/test/scala/com/cra/figaro/test/algorithm/sampling/ImportanceTest.scala, Figaro/src/test/scala/com/cra/figaro/test/algorithm/sampling/MHTest.scala, Figaro/src/test/scala/com/cra/figaro/test/learning/ParameterTest.scala, Figaro/src/test/scala/com/cra/figaro/test/learning/ParameterizedTest.scala, Figaro/src/test/scala/com/cra/figaro/test/library/atomic/continuous/ContinuousTest.scala
Tests for code coverage and online EM
=> Tests for code coverage

Figaro/src/main/scala/com/cra/figaro/algorithm/factored/beliefpropagation/BeliefPropagation.scala, Figaro/src/test/scala/com/cra/figaro/test/language/UniverseTest.scala, Figaro/src/test/scala/com/cra/figaro/test/learning/ParameterTest.scala, Figaro/src/test/scala/com/cra/figaro/test/learning/ParameterizedTest.scala
More code coverage related tests
=> More code coverage related tests

Figaro/src/main/scala/com/cra/figaro/algorithm/Online.scala, Figaro/src/main/scala/com/cra/figaro/algorithm/learning/GeneralizedEM.scala, Figaro/src/main/scala/com/cra/figaro/patterns/learning/ModelParameters.scala
=> Add comments and scaladoc

Figaro/src/test/scala/com/cra/figaro/test/algorithm/learning/EMWithImportanceTest.scala, Figaro/src/test/scala/com/cra/figaro/test/algorithm/learning/EMWithMHTest.scala
Re-submitting pull request for correct merge
=> Fix EMWithMH and EMWithImportance tests

Figaro/src/main/scala/com/cra/figaro/algorithm/factored/MPEVariableElimination.scala, Figaro/src/main/scala/com/cra/figaro/algorithm/factored/beliefpropagation/MPEBeliefPropagation.scala
BPTest and VETest run correcly
=> Fixed MPEVE and MPEBP to convert factors to MaxProduct before inference

Figaro/src/main/scala/com/cra/figaro/library/atomic/continuous/Dirichlet.scala, Figaro/src/test/scala/com/cra/figaro/test/learning/ParameterTest.scala
Correction to previously added test
=> Correction to previously added test

Figaro/src/test/scala/com/cra/figaro/ndtest/BooleanResult.scala, Figaro/src/test/scala/com/cra/figaro/ndtest/NDTest.scala, Figaro/src/test/scala/com/cra/figaro/ndtest/TTestResult.scala, Figaro/src/test/scala/com/cra/figaro/test/algorithm/learning/EMWithImportanceTest.scala, Figaro/src/test/scala/com/cra/figaro/test/algorithm/sampling/ProbEvidenceSamplingTest.scala, Figaro/src/test/scala/com/cra/figaro/test/example/MultiDecisionTest.scala, Figaro/src/test/scala/com/cra/figaro/test/library/atomic/continuous/ContinuousTest.scala
Remove/modify ND tests
Correct some tests
Some tests still need ND modifications added (PBPTest).
Still working on EMWithImportanceTest, ContinuousTest
=> Dev3.1.0 Modifications to improve tests

Figaro/src/test/scala/com/cra/figaro/ndtest/BooleanResult.scala, Figaro/src/test/scala/com/cra/figaro/ndtest/NDTest.scala, Figaro/src/test/scala/com/cra/figaro/ndtest/NDTestResult.scala, Figaro/src/test/scala/com/cra/figaro/ndtest/NoTestResult.scala, Figaro/src/test/scala/com/cra/figaro/ndtest/TTestResult.scala, Figaro/src/test/scala/com/cra/figaro/test/algorithm/learning/EMWithImportanceTest.scala, Figaro/src/test/scala/com/cra/figaro/test/algorithm/learning/ExpectationMaximizationTest.scala, Figaro/src/test/scala/com/cra/figaro/test/algorithm/sampling/MHTest.scala, Figaro/src/test/scala/com/cra/figaro/test/experimental/particlebp/PBPTest.scala, Figaro/src/test/scala/com/cra/figaro/test/library/atomic/continuous/ContinuousTest.scala
Improve reporting of ND tests
Change some tests to ND, eg in PBP
=> Dev3.1.0 Small mods to tests

Figaro/src/test/scala/com/cra/figaro/test/algorithm/learning/EMWithImportanceTest.scala
=> EM test update

Figaro/src/test/scala/com/cra/figaro/test/library/atomic/continuous/ContinuousTest.scala
Used for comparing calculated variance to true (theoretical) variances using T-test
=> Added normal estimator for variance tests

Figaro/src/main/scala/com/cra/figaro/algorithm/sampling/MetropolisHastingsAnnealer.scala, Figaro/src/test/scala/com/cra/figaro/test/algorithm/sampling/AnnealingTest.scala
=> Anytime annealing update

Figaro/src/main/scala/com/cra/figaro/algorithm/learning/GeneralizedEM.scala, Figaro/src/test/scala/com/cra/figaro/test/algorithm/learning/OnlineEMTest.scala
=> Fix OnlineEM bug

Figaro/.gitignore, Figaro/src/main/scala/com/cra/figaro/util/ColorGradient.scala, Figaro/src/main/scala/com/cra/figaro/util/visualization/ResultsGUI.scala, Figaro/src/main/scala/com/cra/figaro/util/visualization/histogram/DataView.scala, Figaro/src/main/scala/com/cra/figaro/util/visualization/histogram/Histogram.scala, Figaro/src/main/scala/com/cra/figaro/util/visualization/histogram/HistogramRenderer.scala, Figaro/src/main/scala/com/cra/figaro/util/visualization/results/ResultsData.scala, Figaro/src/main/scala/com/cra/figaro/util/visualization/results/ResultsTable.scala, Figaro/src/main/scala/com/cra/figaro/util/visualization/results/ResultsView.scala, FigaroExamples/.gitignore, FigaroExamples/src/main/scala/com/cra/figaro/example/visualization/Burglary.scala, FigaroExamples/src/main/scala/com/cra/figaro/example/visualization/ResultsExample.scala, project/Build.scala
Updated examples
Updated ignores
=> Dev3.2.1: Add visualization to utils

Figaro/src/main/scala/com/cra/figaro/util/visualization/ResultsGUI.scala, Figaro/src/main/scala/com/cra/figaro/util/visualization/distribution/Distribution.scala, Figaro/src/main/scala/com/cra/figaro/util/visualization/histogram/Histogram.scala, Figaro/src/main/scala/com/cra/figaro/util/visualization/reduction/DataReduction.scala, Figaro/src/main/scala/com/cra/figaro/util/visualization/results/ResultsView.scala, FigaroExamples/src/main/scala/com/cra/figaro/example/visualization/Burglary.scala, FigaroExamples/src/main/scala/com/cra/figaro/example/visualization/Regression.scala
New Regression example to test visualization
=> Add DataReduction methods to reduce distribution

Figaro/src/main/scala/com/cra/figaro/algorithm/filtering/ParFiltering.scala, Figaro/src/main/scala/com/cra/figaro/algorithm/filtering/ParParticleFilter.scala, Figaro/src/main/scala/com/cra/figaro/algorithm/sampling/ProbQuerySampler.scala, Figaro/src/main/scala/com/cra/figaro/algorithm/sampling/parallel/ParSampler.scala, Figaro/src/main/scala/com/cra/figaro/algorithm/sampling/parallel/ParSamplingAlgorithm.scala, Figaro/src/test/scala/com/cra/figaro/test/algorithm/filtering/ParParticleFilterTest.scala
Adding file headers for various classes and traits related to parallel sampling algorithms.
=> Add file headers.

Figaro/src/main/scala/com/cra/figaro/algorithm/factored/VariableElimination.scala, Figaro/src/test/scala/com/cra/figaro/test/algorithm/factored/VERecursionTest.scala
The test underflows (so fails) but runs to completion
=> #493 Use util.TailCall to elimination recursion in eliminateInOrder

Figaro/src/main/scala/com/cra/figaro/experimental/factored/Gibbs.scala, Figaro/src/main/scala/com/cra/figaro/experimental/structured/algorithm/FlatBP.scala, Figaro/src/main/scala/com/cra/figaro/experimental/structured/algorithm/StructuredVEBPGibbsChooser.scala, Figaro/src/main/scala/com/cra/figaro/experimental/structured/strategy/solve/VEBPGibbsStrategy.scala
Also some minor comments on portions of Gibbs that need to be changed to
support SFI.
=> Added Flat BP, as well as a VE/BP/GS inference strategy.

Figaro/src/main/scala/com/cra/figaro/library/compound/RichCPD.scala
=> Allow RichCPD to use implicit universe, instead of default universe

Figaro/src/main/scala/com/cra/figaro/algorithm/learning/GeneralizedEM.scala
Fixes MH and Importance, but the cause of BP's problems still not known
=> Partial fix for issue #540

Figaro/src/test/scala/com/cra/figaro/test/example/FairDiceTest.scala, FigaroExamples/src/main/scala/com/cra/figaro/example/FairDice.scala
Remove references to Figaro package values
=> Remove references to Figaro package values

Figaro/src/main/scala/com/cra/figaro/algorithm/ProbQueryAlgorithm.scala, Figaro/src/main/scala/com/cra/figaro/algorithm/sampling/Importance.scala, Figaro/src/main/scala/com/cra/figaro/algorithm/sampling/MetropolisHastings.scala, Figaro/src/main/scala/com/cra/figaro/algorithm/sampling/UnweightedSampler.scala, Figaro/src/main/scala/com/cra/figaro/algorithm/sampling/WeightedSampler.scala, Figaro/src/test/scala/com/cra/figaro/test/algorithm/sampling/ImportanceTest.scala, Figaro/src/test/scala/com/cra/figaro/test/algorithm/sampling/MHTest.scala
=> Added sampling jointly from posterior for MH and Importance. Added new

Figaro/src/main/scala/com/cra/figaro/algorithm/factored/VEGraph.scala, Figaro/src/main/scala/com/cra/figaro/algorithm/factored/VariableElimination.scala, Figaro/src/main/scala/com/cra/figaro/algorithm/factored/beliefpropagation/BeliefPropagation.scala, Figaro/src/main/scala/com/cra/figaro/algorithm/lazyfactored/LazyVariableElimination.scala, Figaro/src/main/scala/com/cra/figaro/algorithm/structured/solver/BPSolver.scala, Figaro/src/test/scala/com/cra/figaro/test/algorithm/factored/VETest.scala
VariableOrdering to get the total cost of eliminiation, and make the
iterations in BP a def instead of a val
=> Minor changes in VE/BP to support optimization. In particular, overload

Figaro/src/main/scala/com/cra/figaro/algorithm/structured/ComponentCollection.scala
These changes address issue #574
=> updates to ComponentCollection.scala

Figaro/src/main/scala/com/cra/figaro/experimental/collapsedgibbs/CollapsedGibbs.scala, Figaro/src/main/scala/com/cra/figaro/experimental/collapsedgibbs/CollapsedProbQueryGibbs.scala, Figaro/src/main/scala/com/cra/figaro/experimental/collapsedgibbs/Collapsers.scala, Figaro/src/test/scala/com/cra/figaro/test/algorithm/factored/experimental/CollapsedGibbsTest.scala
These files provide an implementation of the Collapsed Gibbs sampler given in "Dynamic Blocking and Collapsing for Gibbs Sampling". (Gogate and Venugopal 2013)
=> New sampling algorithm: Collapsed Gibbs Sampler

Figaro/src/main/scala/com/cra/figaro/library/atomic/continuous/Exponential.scala, Figaro/src/main/scala/com/cra/figaro/library/atomic/continuous/Gamma.scala, Figaro/src/main/scala/com/cra/figaro/library/atomic/continuous/InverseGamma.scala, Figaro/src/main/scala/com/cra/figaro/library/atomic/continuous/KernelDensity.scala, Figaro/src/main/scala/com/cra/figaro/library/atomic/continuous/MultivariateNormal.scala, Figaro/src/main/scala/com/cra/figaro/library/atomic/continuous/Normal.scala, Figaro/src/main/scala/com/cra/figaro/library/atomic/continuous/Uniform.scala, Figaro/src/test/scala/com/cra/figaro/test/library/atomic/continuous/ContinuousTest.scala
Added tests for Continuous trait
=> Dev4.1 - Make classes in continuous package extend Continuous trait

Figaro/src/main/scala/com/cra/figaro/algorithm/factored/FactoredAlgorithm.scala, Figaro/src/main/scala/com/cra/figaro/algorithm/factored/beliefpropagation/BeliefPropagation.scala, Figaro/src/main/scala/com/cra/figaro/algorithm/factored/factors/factory/ChainFactory.scala, Figaro/src/main/scala/com/cra/figaro/algorithm/factored/factors/factory/Factory.scala, Figaro/src/main/scala/com/cra/figaro/algorithm/lazyfactored/LazyValues.scala, Figaro/src/main/scala/com/cra/figaro/algorithm/learning/GeneralizedEM.scala, Figaro/src/main/scala/com/cra/figaro/algorithm/sampling/Importance.scala, Figaro/src/main/scala/com/cra/figaro/language/Element.scala, Figaro/src/test/scala/com/cra/figaro/test/algorithm/learning/EMWithMHTest.scala, Figaro/src/test/scala/com/cra/figaro/test/algorithm/structured/strategy/FlatTest.scala, Figaro/src/test/scala/com/cra/figaro/test/algorithm/structured/strategy/StructuredBPTest.scala, Figaro/src/test/scala/com/cra/figaro/test/algorithm/structured/strategy/StructuredVEBPChooserTest.scala, Figaro/src/test/scala/com/cra/figaro/test/algorithm/structured/strategy/StructuredVEGibbsChooserTest.scala, Figaro/src/test/scala/com/cra/figaro/test/algorithm/structured/strategy/StructuredVETest.scala
Issue #658 fixed for Importance sampling only.
=> Changes for parameter factor creation. Fix for issues #659 and #660.

Figaro/src/main/scala/com/cra/figaro/algorithm/factored/factors/ConstraintFactor.scala, Figaro/src/main/scala/com/cra/figaro/algorithm/factored/factors/factory/ApplyFactory.scala, Figaro/src/main/scala/com/cra/figaro/algorithm/structured/algorithm/laziness/LazyVE.scala, Figaro/src/main/scala/com/cra/figaro/algorithm/structured/strategy/refine/package.scala
=> Added first crack at Lazy VE. Also made some speed improvements making

Figaro/src/main/scala/com/cra/figaro/algorithm/structured/algorithm/StructuredProbQueryAlgorithm.scala
=> Return ProblemComponents along with distribution results

Figaro/src/main/scala/com/cra/figaro/util/visualization/distribution/Distribution.scala, Figaro/src/main/scala/com/cra/figaro/util/visualization/histogram/Histogram.scala, Figaro/src/main/scala/com/cra/figaro/util/visualization/results/ResultsView.scala, Figaro/src/test/scala/com/cra/figaro/test/algorithm/factored/VETest.scala, Figaro/src/test/scala/com/cra/figaro/test/example/MultiValuedTest.scala, Figaro/src/test/scala/com/cra/figaro/test/util/PriorityMapTest.scala, Figaro/src/test/scala/com/cra/figaro/test/util/SelectableSetTest.scala, Figaro/src/test/scala/com/cra/figaro/test/util/UtilTest.scala
Also replace JavaConversions with JavaConverters
=> Handle eta expansion deprecation

Figaro/src/main/scala/com/cra/figaro/algorithm/factored/factors/factory/ApplyFactory.scala, Figaro/src/main/scala/com/cra/figaro/algorithm/factored/factors/factory/Factory.scala, Figaro/src/main/scala/com/cra/figaro/algorithm/lazyfactored/LazyValues.scala, Figaro/src/main/scala/com/cra/figaro/algorithm/lazyfactored/ValueSet.scala
Added a normalizing term to ValueSet so that when factors are created,
we can pull this normalizing factor and multiply it into the sampled
factors.
=> Changes to ensure factors are normalized in expectation when sampling factors
